<?php
/** @var Mage_Customer_Block_Form_Register $this */
?>
<?php
$refererHelper = Mage::helper('snowreferefiframe');
?>
<div class="account-login account-login--create">
    <h1 class="account-login__title"><?php echo $this->__('Create an Account'); ?></h1>
    <?php echo $this->getChildHtml('form_fields_before'); ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>

    <div class="access-code-popup">
        <div class="overlay"></div>
        <div class="popup-info">
            <p class="popup-text">
                <?php echo $this->__('Venus Skin products are available exclusively through participating clinics and physicians offices. If you do not have an Exclusive Access Code, click "generate a code" below.'); ?>
            </p>
            <button class="button"><?php echo $this->__('Generate A Code'); ?></button>
        </div>
    </div>

    <p class="account-login__description">
        <strong><?php echo $this->__('Are you a Physician?'); ?></strong>
        <?php echo $this->__('If you are a physician looking to add Venus Skin to your practice, please <a href="%s">click here</a> to contact our team.', $this->getUrl('contact')); ?>
    </p>

    <form action="<?php echo $this->getPostActionUrl(); ?>" method="post" id="form-validate"
          enctype="multipart/form-data">
        <div class="account-login__row">
            <div class="account-login__col account-login__col--left">
                <div class="account-login__content">
                    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl(); ?>"/>
                    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl(); ?>"/>
                    <input type="hidden" name="invitation_id" value="<?php echo $this->getRequest()->getParam('invitation_id'); ?>" />
                    <h3 class="account-login__subtitle">
                        <?php echo $this->__('Personal Information'); ?>
                    </h3>
                    <ul class="form-list">
                        <li>
                            <label for="referral_code" class="required">
                                <em>*</em><?php echo $this->__('Exclusive Access Code'); ?>&nbsp;<span
                                        class="code-prompt"><?php echo $this->__('(Click here if you don\'t have an access code)'); ?></span>
                            </label>
                            <div class="input-box">
                                <input type="text"
                                       name="<?php echo Snowdog_Multilevel_Helper_Data::PARAM_REFERRAL_KEY; ?>"
                                       id="referral_code" title="<?php echo $this->__('Exclusive Access Code'); ?>"
                                       class="input-text required-entry"
                                       readonly="true"
                                       value="<?php echo ($this->getRequest()->getParam('acc')) ? $this->getRequest()->getParam('acc') : $refererHelper->getAcc(); ?>"/>
                            </div>
                        </li>
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml(); ?>
                        </li>
                        <li>
                            <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address'); ?></label>

                            <div class="input-box">
                                <input type="email" name="email" id="email_address"
                                       value="<?php if ($this->getRequest()->getParam('email')) {
                                           echo $this->getRequest()->getParam('email');
                                       }else {
                                           echo $this->escapeHtml($this->getFormData()->getEmail());
                                       } ?>"
                                       title="<?php echo $this->__('Email Address');
                                       ?>" class="input-text validate-email required-entry"/>
                            </div>
                        </li>
                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob'); ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml(); ?></li>
                        <?php endif ?>
                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml(); ?></li>
                        <?php endif ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender'); ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml(); ?></li>
                        <?php endif ?>
                        <?php $customerAttributes = $this->getChild('customer_form_user_attributes'); ?>
                        <?php if ($customerAttributes): ?>
                            <?php $customerAttributes->setShowContainer(false); ?>
                            <?php $this->restoreSessionData($customerAttributes->getForm()); ?>
                            <?php echo $customerAttributes->toHtml(); ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
            <?php if ($this->getShowAddressFields()): ?>
                <div class="fieldset right">
                    <input type="hidden" name="create_address" value="1"/>
                    <h3><?php echo $this->__('Address Information'); ?></h3>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="company">
                                    <?php echo $this->__('Company'); ?>
                                </label>
                                <div class="input-box">
                                    <input type="text" name="company" id="company"
                                           value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()); ?>"
                                           title="<?php echo $this->__('Company'); ?>"
                                           class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company'); ?>"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="telephone" class="required">
                                    <em>*</em><?php echo $this->__('Telephone'); ?>
                                </label>
                                <div class="input-box">
                                    <input type="text" name="telephone" id="telephone"
                                           value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()); ?>"
                                           title="<?php echo $this->__('Telephone'); ?>"
                                           class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone'); ?>"/>
                                </div>
                            </div>
                        </li>
                        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="wide">
                            <label for="street_1" class="required">
                                <em>*</em><?php echo $this->__('Street Address'); ?>
                            </label>
                            <div class="input-box">
                                <input type="text" name="street[]"
                                       value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)); ?>"
                                       title="<?php echo $this->__('Street Address'); ?>" id="street_1"
                                       class="input-text <?php echo $_streetValidationClass ?>"/>
                            </div>
                        </li>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <li class="add-field">
                                <div class="input-box">
                                    <input type="text" name="street[]"
                                           value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)); ?>"
                                           title="<?php echo $this->__('Street Address %s', $_i); ?>"
                                           id="street_<?php echo $_i ?>"
                                           class="input-text <?php echo $_streetValidationClass ?>"/>
                                </div>
                            </li>
                        <?php endfor; ?>
                        <li class="fields">
                            <div class="field">
                                <label for="city" class="required">
                                    <em>*</em><?php echo $this->__('City'); ?>
                                </label>
                                <div class="input-box">
                                    <input type="text" name="city"
                                           value="<?php echo $this->escapeHtml($this->getFormData()->getCity()); ?>"
                                           title="<?php echo $this->__('City'); ?>"
                                           class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city'); ?>"
                                           id="city"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="region_id" class="required">
                                    <em>*</em><?php echo $this->__('State/Province'); ?>
                                </label>
                                <div class="input-box">
                                    <select id="region_id" name="region_id"
                                            title="<?php echo $this->__('State/Province'); ?>" class="validate-select"
                                            style="display:none;">
                                        <option value="">
                                            <?php echo $this->__('Please select region, state or province'); ?>
                                        </option>
                                    </select>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId(); ?>");
                                        //]]>
                                    </script>
                                    <input type="text" id="region" name="region"
                                           value="<?php echo $this->escapeHtml($this->getRegion()); ?>"
                                           title="<?php echo $this->__('State/Province'); ?>"
                                           class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region'); ?>"
                                           style="display:none;"/>
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="zip" class="required">
                                    <em>*</em><?php echo $this->__('Zip/Postal Code'); ?>
                                </label>
                                <div class="input-box">
                                    <input type="text" name="postcode"
                                           value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()); ?>"
                                           title="<?php echo $this->__('Zip/Postal Code'); ?>" id="zip"
                                           class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode'); ?>"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="country" class="required">
                                    <em>*</em><?php echo $this->__('Country'); ?>
                                </label>
                                <div class="input-box">
                                    <?php echo $this->getCountryHtmlSelect(); ?>
                                </div>
                            </div>
                        </li>
                        <?php $addressAttributes = $this->getChild('customer_form_address_user_attributes'); ?>
                        <?php if ($addressAttributes): ?>
                            <?php $addressAttributes->setEntity($this->getAddress()); ?>
                            <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                            <?php $this->restoreSessionData($addressAttributes->getForm(), 'address'); ?>
                            <?php echo $addressAttributes->setShowContainer(false)->toHtml(); ?>
                        <?php endif; ?>
                    </ul>
                    <input type="hidden" name="default_billing" value="1"/>
                    <input type="hidden" name="default_shipping" value="1"/>
                </div>
            <?php endif; ?>
            <div class="account-login__col account-login__col--right">
                <div class="account-login__content">
                    <h3 class="account-login__subtitle"><?php echo $this->__('Login Information'); ?></h3>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="password" class="required">
                                    <em>*</em><?php echo $this->__('Password'); ?>
                                </label>
                                <div class="input-box">
                                    <input type="password" name="password" id="password"
                                           title="<?php echo $this->__('Password'); ?>"
                                           class="input-text required-entry validate-password"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="confirmation" class="required">
                                    <em>*</em><?php echo $this->__('Confirm Password'); ?></label>
                                <div class="input-box">
                                    <input type="password" name="confirmation"
                                           title="<?php echo $this->__('Confirm Password'); ?>" id="confirmation"
                                           class="input-text required-entry validate-cpassword"/>
                                </div>
                            </div>
                            <div class="field">
                                <label for="country" class="required">
                                    <em>*</em><?php echo $this->__('Country') ?>
                                </label>
                                <div class="input-box">
                                    <?php echo $this->getCountryHtmlSelect() ?>
                                </div>
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <div class="buttons-set form-buttons">
                        <div class="clearfix">
                            <a class="account-login__back left"
                               href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>">
                                <small>&laquo; </small><?php echo $this->__('Back'); ?>
                            </a>
                            <p class="required right">
                                <?php echo $this->__('* Required Fields'); ?>
                            </p>
                        </div>
                        <button type="submit" class="button" title="<?php echo $this->__('Sign up'); ?>">
                            <span><span><?php echo $this->__('Sign up'); ?></span></span>
                        </button>
                    </div>
                    <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                        <input name="context" type="hidden" value="checkout"/>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson(); ?>, undefined, 'zip');
        <?php endif; ?>

        Form.getElements('form-validate').each(function(element) {
            element.setAttribute('autocomplete', 'off');
        });
        //]]>

        /* ---- Generic Access Code Button ---- */
        var accessOverlay = jQuery('.access-code-popup');

        jQuery('span.code-prompt').click(function () {
            var that = $(this);
            accessOverlay.addClass('active');
        });

        accessOverlay.on('click', '.overlay', function () {
            accessOverlay.removeClass('active');
        });

        jQuery('.access-code-popup button.button').on('click', function () {
            jQuery('#referral_code').val(<?php echo $this->helper('core')->jsonEncode(Mage::helper('multilevel')->getDefaultDoctor()->getIdentifyCode()); ?>);
            accessOverlay.find('.overlay').trigger('click');
        });
    </script>
</div>
