<?php
$_order = $this->getOrder();
?>

<div class="order-page">
	<div class="page-title title-buttons">
		<h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()); ?></h1>
	</div>

	<div class="order-info-buttons">
		<?php echo $this->getChildHtml('buttons'); ?>
	</div>

	<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
	<?php echo $this->getStatusHistoryRssUrl($_order); ?>

	<div class="order-info-container">
		<dl class="order-info">
			<dt><?php echo $this->__('About This Order:'); ?></dt>
			<dd>
				<?php $_links = $this->getLinks(); ?>
				<ul>
					<?php foreach ($_links as $_link): ?>
						<?php if ($_link->getUrl()): ?>
							<li><a class="button button-dark" href="<?php echo $_link->getUrl(); ?>"><?php echo $_link->getLabel(); ?></a></li>
						<?php else: ?>
							<li class="current"><span class="button button-dark button-current"><?php echo $_link->getLabel(); ?></span></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</dd>
		</dl>

		<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')); ?></p>
	</div>

	<?php if (!$_order->getIsVirtual()): ?>
		<div class="col2-set">
			<div class="col-1">
				<div class="info-box">
					<h3 class="box-title"><?php echo $this->__('Shipping Address'); ?></h3>
					<address class="box-content"><?php echo $_order->getShippingAddress()->format('html'); ?></address>
				</div>
			</div>
			<div class="col-2">
				<div class="info-box">
					<h3 class="box-title"><?php echo $this->__('Shipping Method'); ?></h3>

					<div class="box-content">
						<?php if ($_order->getShippingDescription()): ?>
							<?php echo $this->escapeHtml($_order->getShippingDescription()); ?>
						<?php else: ?>
							<?php echo $this->helper('sales')->__('No shipping information available'); ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<div class="col2-set">
		<div class="col-1">
			<div class="info-box">
				<h3 class="box-title"><?php echo $this->__('Billing Address'); ?></h3>
				<address class="box-content"><?php echo $_order->getBillingAddress()->format('html'); ?></address>
			</div>
		</div>
		<div class="col-2">
			<div class="info-box">
				<h3 class="box-title"><?php echo $this->__('Payment Method'); ?></h3>

				<div class="box-content"><?php echo $this->getPaymentInfoHtml(); ?></div>
			</div>
		</div>
	</div>
</div>
