<?php
/**
 * Banana ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@advancedcontentmanager.com so we can send you a copy immediately.
 *
 * @category	Banana
 * @package		Banana_ContentManager
 * @copyright	Copyright (c) 2014 Banana Content Manager (http://www.advancedcontentmanager.com)
 * @author		Banana Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.2.4
 */
?>
<table style="border: 0 none;">
    <tbody style="background: none;">
        
        <?php 
            $stores = Mage::getModel('core/store')->getCollection();
            $content = Mage::getModel('contentmanager/content')->setStoreId(0)->load($this->getEntityId());
            if($content->existsForStore(0))
            {
                $flag_img = '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'contenttype/flags/world.png'.'" /> ';            
                if($content->getData($this->getColumn()->getIndex()) !== null): ?>
                    <tr><td style="border: 0 none;">
                    <?php echo $flag_img.$this->helper('core')->formatDate($content->getData($this->getColumn()->getIndex()), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT).' '.$this->helper('core')->formatTime($content->getData($this->getColumn()->getIndex()), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT).'<br />'; ?>
                    </td></tr>
                <?php endif; 
            }
            
            foreach($stores as $store)
            {
                $content = Mage::getModel('contentmanager/content')->setStoreId($store->getId())->load($this->getEntityId());
                
                if($content->existsForStore($store->getId()))
                {
                    $flag = Mage::getModel('contentmanager/flag')->load($store->getId());
                    $flag_img = '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'contenttype/flags/'.$flag->getValue().'" /> ';
        
                    if($content->getData($this->getColumn()->getIndex()) !== null): ?>
                        <tr><td style="border: 0 none;">
                        <?php echo $flag_img.$this->helper('core')->formatDate($content->getData($this->getColumn()->getIndex()), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT).' '.$this->helper('core')->formatTime($content->getData($this->getColumn()->getIndex()), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT).'<br />'; ?>
                        </td></tr>
                    <?php endif; 
                }
            }
        ?>
    </tbody>
</table>
