<div class="physician-contact-block">
	<form action="<?php echo $this->getUrl('contacts/index/post'); ?>" id="contactForm" method="post">
		<div class="fieldset">
			<div class="form-header">
				<h4><?php echo Mage::helper('contacts')->__('Get In Touch'); ?></h4>
				<hr />
				<p><?php echo $this->__('Please supply us with your contact information so that we can tell you more about our amazing skincare line and enroll you in our program.'); ?></p>
			</div>
			<ul class="form-list">
				<li class="fields">
					<div class="field">
						<label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>

						<div class="input-box">
							<input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
						</div>
					</div>
					<div class="field">
						<label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>

						<div class="input-box">
							<input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" />
						</div>
					</div>
					<div class="field">
						<label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>

						<div class="input-box">
							<input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
						</div>
					</div>
				</li>
				<li class="wide">
					<div class="field">
						<label for="region"><?php echo Mage::helper('contacts')->__('State/Province') ?></label>

						<div class="input-box">
							<input name="region" id="region" title="<?php echo Mage::helper('contacts')->__('State/Province') ?>" value="" class="input-text" type="text" />
						</div>
					</div>

					<label for="comment"><?php echo Mage::helper('contacts')->__('Comment') ?></label>

					<div class="input-box">
						<textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="input-text" cols="5" rows="3"></textarea>
					</div>
				</li>
			</ul>
		</div>
		<div class="buttons-set">
			<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />

			<p class="required left"><?php echo Mage::helper('contacts')->__('Required Fields *') ?></p>
			<button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button right" onclick="submitForms(event)">
				<span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span>
			</button>
		</div>
	</form>

	<form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST" id="salesforceForm">
		<input type=hidden name="oid" value="00Di0000000aYqF">
		<input type=hidden name="retURL" value="<?php echo $this->escapeHtml(Mage::helper('cms/page')->getPageUrl('contact-thank-you')); ?>">
		<input type="hidden" id="salesforce_first_name" name="first_name" />
		<input type="hidden" id="salesforce_last_name" name="last_name" />
		<input type="hidden" id="salesforce_email" name="email" />
	</form>

	<script type="text/javascript">
	//<![CDATA[
	var contactForm = new VarienForm('contactForm', false);
	//]]>

	function submitForms(e) {
		e.preventDefault();
		var nameArray = jQuery('#name').val().split(/[\s,]+/);
		if (nameArray.length > 0) {
			var firstName = nameArray[0];
			jQuery('#salesforce_first_name').val(firstName);
		}
		if (nameArray.length > 1) {
			var lastName = nameArray[1];
			jQuery('#salesforce_last_name').val(lastName);
		}
		jQuery('#salesforce_email').val(jQuery('#email').val());

		if (contactForm.submit()) {
			jQuery('#salesforceForm').submit();
		}
	}

	</script>
</div>
