<?php
/**
 * @var $this Enterprise_TargetRule_Block_Catalog_Product_Item
 */

$_helper = $this->helper('catalog/output');
$_product = $this->getProduct() ? : $this->getItem();

if ($_product) : ?>

	<a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,230); ?>" width="270" height="230" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
	<div class="product-info">
		<h3><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
		<div class="price-options">
			<?php echo $this->getPriceHtml($_product, true) ?>
			<a class="button" href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('View Product'); ?></a>
		</div>
	</div>

<?php endif; ?>
