<?php
/**
 * Banana ContentManager Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@advancedcontentmanager.com so we can send you a copy immediately.
 *
 * @category	Banana
 * @package		Banana_ContentManager
 * @copyright	Copyright (c) 2014 Banana Content Manager (http://www.advancedcontentmanager.com)
 * @author		Banana Team
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version		1.2.4
 */
?>
<script type="text/javascript">

OptionTemplateDate = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
            '<th class="type-last last"><?php echo Mage::helper('catalog')->__('Default value') ?> </th>'+
        '</tr>'+
        '<tr>'+
            '<td class="value"><input type="text" class="input-text" name="contenttype[options][{{option_id}}][default_value]" value="{{default_value}}"></td>'+
        '</tr>'+
    '</table>'+
    '<p class="note"><span>Respect date format: <?php echo $this->__('mm/dd/yyyy hh:mm a'); ?>, type "&lt;now&gt;" in order to automatically fill the field with current date.</span></p>';

if ($('option_panel_type_date')) {
    $('option_panel_type_date').remove();
}

</script>
