<footer class="footer">
    <div class="footer__container">
        <div class="footer__logo">
            <img src="<?= $this->getSkinUrl('images/footer/footer_logo.png'); ?>">
        </div>
        <?= $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
        <?= $this->getLayout()->createBlock('cms/block')->setBlockId('footer_social')->toHtml() ?>
    </div>
</footer>
