<?php
/** @var Venus_Registration_Block_Landing $this */
?>
<h4 class="fieldset-title"><?php echo $this->__('Registration Information'); ?></h4>

<div class="fieldset">
	<input type="hidden" name="<?php echo Venus_Multilevel_Helper_Data::PARAM_REFERRAL_KEY; ?>" id="referral_code" value="<?php echo Mage::helper('multilevel')->getDefaultDoctor()->getAffiliateAccount()->getIdentifyCode(); ?>" />
	<input type="hidden" name="redirect_here" id="redirect_here" value="1" />

	<ul class="form-list">
		<li class="fields">
			<div class="field left">
				<label for="firstname" class="required"><em>*</em><?php echo Mage::helper('registration')->__('First Name'); ?></label>

				<div class="input-box">
					<input name="firstname" id="firstname" title="<?php echo Mage::helper('registration')->__('First Name'); ?>" class="input-text required-entry" type="text" />
				</div>
			</div>

			<div class="field right">
				<label for="lastname" class="required"><em>*</em><?php echo Mage::helper('registration')->__('Last Name'); ?></label>

				<div class="input-box">
					<input name="lastname" id="lastname" title="<?php echo Mage::helper('registration')->__('Last Name'); ?>" class="input-text required-entry" type="text" />
				</div>
			</div>
		</li>

		<li class="fields">
			<div class="field">
				<label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email'); ?></label>

				<div class="input-box">
					<input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email'); ?>" class="input-text required-entry validate-email" type="email" />
				</div>
			</div>

			<div class="field right">
				<label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>

				<div class="input-box">
					<?php echo $this->getCountryHtmlSelect(); ?>
				</div>
			</div>
		</li>

		<li class="fields">
			<div class="field left">
				<label for="password" class="required"><em>*</em><?php echo $this->__('Password'); ?></label>

				<div class="input-box">
					<input type="password" name="password" id="password" title="<?php echo $this->__('Password'); ?>" class="input-text required-entry validate-password" />
				</div>
			</div>

			<div class="field right">
				<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password'); ?></label>

				<div class="input-box">
					<input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password'); ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
				</div>
			</div>
		</li>
	</ul>
</div>

<script type="text/javascript">
//<![CDATA[
Form.getElements('registrationForm').each(function (element) {
	element.setAttribute('autocomplete', 'off');
});
//]]>
</script>
