<div class="buttons-set">
	<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />

	<p class="required left"><?php echo Mage::helper('contacts')->__('Required Fields *') ?></p>

	<button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button right">
		<span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span>
	</button>
</div>
