<h4 class="fieldset-title"><?php echo $this->__('Login Information (Existing accounts only)'); ?></h4>

<div class="fieldset">
	<ul class="form-list">
		<li class="fields">
			<div class="field left">
				<label for="login_email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>

				<div class="input-box">
					<input name="login[username]" id="login_email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" class="input-text required-entry validate-email" type="email" />
				</div>
			</div>
			<div class="field right">
				<label for="login_password" class="required"><em>*</em><?php echo $this->__('Password'); ?></label>

				<div class="input-box">
					<input type="password" name="login[password]" id="login_password" title="<?php echo $this->__('Password'); ?>" class="input-text required-entry validate-password" />
				</div>
			</div>
		</li>
	</ul>
</div>
