<?php
/**
 * Tier Commissions template
 */
?>
<?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid() ?>
<?php $_name = $this->getElement()->getName() ?>
<?php $_maxLevel = $this->getMaxLevel() ?>
<?php $_arrayRows = $this->getArrayRows() ?>

<div class="grid" id="<?php echo $_htmlId ?>">
	<table cellpadding="0" cellspacing="0" class="border">
		<tbody>
			<tr class="headings" id="headings<?php echo $_htmlId ?>">
				<th><?php echo $this->__('Level') ?></th>
				<th><?php echo $this->__('Range') ?></th>
				<th><?php echo $this->__('Commission Value') ?></th>
			</tr>
			<tr id="<?php echo $_htmlId ?>1">
				<td><?php echo $this->__('Sales Level %d', 1) ?></td>
				<td>
					<strong>&gt; <?php echo $this->__('%d', 0) ?></strong>
				</td>
				<td>
					<strong><?php echo $this->getDefaultCommission() ?></strong>
				</td>
			</tr>
			<?php $_defaultRows = new Varien_Object() ?>
			<?php for ($_i = 2; $_i <= $_maxLevel; $_i++): ?>
				<?php $_rowData = isset($_arrayRows[$_i]) ? $_arrayRows[$_i] : $_defaultRows ?>
				<tr id="<?php echo $_htmlId . $_i ?>">
					<td><?php echo $this->__('Sales Level %d', $_i) ?></td>
					<td>
						<div>
							<strong>&gt; </strong><input type="text" name="<?php echo $_name ?>[<?php echo $_i ?>][range]" class="input-text" value="<?php echo $_rowData->getRange() ?>" style="width: 49px;" />
						</div>
					</td>
					<td>
						<input type="text" name="<?php echo $_name ?>[<?php echo $_i ?>][value]" class="input-text" value="<?php echo $_rowData->getValue() ?>" style="width: 49px;" />
					</td>
				</tr>
			<?php endfor ?>
		</tbody>
	</table>
</div>

<?php if ($this->getElement()->getDisabled()): ?>
	<script type="text/javascript">
	toggleValueElements({checked: true}, $('<?php echo $_htmlId ?>').parentNode);
	</script>
<?php endif ?>
