<?php
$themeOptions = $this->helper('idstore');

if ($themeOptions->useTwitter()): ?>
    <span class="footer-title"><?php echo $this->__('Recent Tweets'); ?></span>
    <?php echo $this->getChildHtml('twitter_feed'); ?>
<?php else :
    $title = Mage::getModel('cms/block')
    ->setStoreId(Mage::app()->getStore()->getId())
    ->load('cms_twitter')
    ->getTitle();
?>
    <span class="footer-title"><?php echo $title ?></span>
    <?php echo $this->getChildHtml('cms_twitter'); ?>
<?php endif ?>
