<meta name="globalsign-domain-verification" content="FCncfishWvrfvAuj6vWNOSurKCONSrXQEIlPDJpilg" />
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
