<?php
$_order = $this->getOrder();
?>

<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
	<a class="button button-dark" href="<?php echo $this->getReorderUrl($_order); ?>"><?php echo $this->__('Reorder'); ?></a>
<?php endif ?>

<a class="button button-dark" href="<?php echo $this->getPrintUrl($_order); ?>" onclick="this.target='_blank';"><?php echo $this->__('Print Order'); ?></a>

<?php if ($this->helper('rss/order')->isStatusNotificationAllow()): ?>
	<a class="button button-dark" href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order); ?>" class="link-rss f-none"><?php echo $this->__('Subscribe to Order Status'); ?></a>
<?php endif; ?>

<?php echo $this->getChildHtml(); ?>
