<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper            = $this->helper('catalog/output');
?>

<div class="owl-carousel products-grid">
	<?php foreach ($_productCollection as $_product): ?>
		<div>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(500); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

			<div class="product-info">
				<h3 class="product-name">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
				</h3>

				<div class="price-info">
					<?php echo $this->getPriceHtml($_product, true) ?>
					<i class="icon icon-info-sign vip-banner-button" title="<?php echo $this->__('What is VIP?'); ?>"></i>
				</div>

				<div class="price-options">
					<div class="actions">
						<?php if ($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
								<span><span><?php echo $this->__('Add to Cart') ?></span></span>
							</button>

							<button type="button" title="<?php echo $this->__('Learn More') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
								<span><span><?php echo $this->__('Learn More') ?></span></span>
							</button>
						<?php elseif (!$_product->getIsSalable()): ?>
							<div class="button out-of-stock">
								<span class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></span>
							</div>
						<?php endif; ?>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach ?>
</div>

<script type="text/javascript">
jQuery('.owl-carousel').owlCarousel({
	responsive: {
		0   : {
			items: 1,
			nav  : true
		},
		628 : {
			items: 2,
			nav  : true
		},
		970 : {
			items: 3,
			nav  : true
		},
		1180: {
			items: 3,
			nav  : true
		}
	},
	loop      : false,
	margin    : 15
});
</script>
