<?php
$_order = $this->getOrder();
?>

<div class="order-page">
	<div class="page-title title-buttons">
		<h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()); ?></h1>
		<?php echo $this->getChildHtml('buttons'); ?>
	</div>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php echo $this->getStatusHistoryRssUrl($_order); ?>

<div class="order-info-container">
	<dl class="order-info">
		<dt><?php echo $this->__('About This Order:'); ?></dt>
		<dd>
			<?php $_links = $this->getLinks(); ?>
			<ul>
				<?php foreach ($_links as $_link): ?>
					<?php if ($_link->getUrl()): ?>
						<li><a class="button button-dark" href="<?php echo $_link->getUrl(); ?>"><?php echo $_link->getLabel(); ?></a></li>
					<?php else: ?>
						<li class="current"><span class="button button-dark button-current"><?php echo $_link->getLabel(); ?></span></li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</dd>
	</dl>

	<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')); ?></p>
</div>
