<?php
/**
 * @var Mage_Checkout_Block_Total_Nominal $this
 */
?>
<?php
/*
<tr>
	<th colspan="<?php echo $this->getColspan() + 1; ?>" style="<?php echo $this->getTotalStyle() ?>" class="a-right">
		<?php echo sprintf(($this->getRenderingArea() == $this->getTotalArea()) ? '<strong>%s</strong>' : '%s', $this->escapeHtml($this->getTotalTitle())) ?>
	</th>
</tr>
*/
?>
<?php
	$totals = 0;
	$nominalItems = 0;
?>
<?php foreach ($this->getTotalItems() as $i => $item): ?>
	<?php
		$totals += $this->getItemRowTotal($item);
		$_nominalItems++;
	?>
<?php endforeach; ?>

<tr class="summary-total">
	<td colspan="<?php echo $this->getColspan(); ?>"
		style="<?php echo $this->getTotalStyle() ?>"
		class="a-right">
		<?php echo $this->__('Grand Total'); //$this->escapeHtml($this->getItemName($item)); ?>
		<span class="summary-total__info">(<?php echo $this->__('For %s
		recurring products',
				$_nominalItems);	?>)</span>
	</td>
	<td class="a-right">
		<?php echo $this->helper('checkout')->formatPrice
		($totals, false) ?>
	</td>
</tr>

