<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to cart'); ?>
<?php if ($_product->isSaleable()): ?>
	<button type="submit" title="<?= $buttonTitle ?>" class="add-to-cart product-shop__actions-to-cart">
		<?= $buttonTitle ?>
	</button>
	<?= $this->getChildHtml('', true, true) ?>
<?php else: ?>
	<div class="out-of-stock left">
		<?= $this->__('Out Of Stock'); ?>
	</div>
<?php endif; ?>
