<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<div class="home-section home-bestseller">
    <div class="home-bestseller__container">
        <ul class="home-bestseller__heading">
            <li class="home-bestseller__heading-item">
                <span class="home-bestseller__title">SHOP BEST SELLERS</span>
            </li>
            <li class="home-bestseller__heading-item">
                <a class="home-bestseller__link" href="<?php echo Mage::getBaseUrl(); ?>products">SHOP ALL</a>
            </li>
        </ul>
        <div class="home-bestseller__row">
            <ul class="products-grid home-bestseller__products">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item home-bestseller__product">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image"><img
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(500); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>

                        <div class="product-info">
                            <h3 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                            </h3>

                            <div class="price-info">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <i class="icon icon-info-sign vip-banner-button"
                                   title="<?php echo $this->__('What is VIP?'); ?>"></i>
                            </div>

                            <div class="price-options">
                                <div class="actions">
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                class="button btn-cart"
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                        </button>

                                        <button type="button" title="<?php echo $this->__('Learn More') ?>"
                                                class="button btn-cart"
                                                onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                            <span><span><?php echo $this->__('Learn More') ?></span></span>
                                        </button>
                                    <?php elseif (!$_product->getIsSalable()): ?>
                                        <div class="button out-of-stock">
                                             <span class="availability out-of-stock">
                                                 <span><?php echo $this->__('Out of Stock') ?></span>
                                             </span>
                                        </div>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                                   class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>

                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>

<div class="modal-content">
    <div class="vip-modal">
        <h2>Are You a <strong>VIP</strong> Member?</h2>
        <hr>
        <p>Never run out of your favourite products!</p>
        <p>Automatic 30, 45, or 60 day delivery options.</p>
        <p>Special "Members-Only" pricing as a valued member of our program.</p>
        <p>Exclusive access to promotions and insider information.</p>
        <p><strong>Free to join, cancel at any time!</strong></p>
        <a href="<?php echo Mage::getBaseUrl(); ?>customer/account/create" class="button transparent join-now">
            Join Now
        </a>
    </div>
</div>

<script type="text/javascript">
    jQuery(function($) {
        $('.vip-banner, .vip-banner-button').on('click', function() {
            LiteModal.create({
                overlayClose: true,
                buttonClose: true,
                content: $('.modal-content').html()
            });
        })
    });
</script>
