<div class="banner-give-get">
	<div class="inner">
		<h2><?php echo $this->__('Give $100, Get $100') ?></h2>

		<p><?php echo $this->__('The program that rewards you and your friends for using our products.'); ?></p>
		<a class="button learn-more" href="<?php echo Mage::helper('cms/page')->getPageUrl('forpatients'); ?>#give-get-banner">
			<?php echo $this->__('Learn More'); ?>
		</a>
	</div>
</div>
